# Example - Complex
#
# Agent running with a more complex configuration

FROM oneapm/docker-oneapm-ci-agent

# Add a constom cloudinsight-agent.conf
ADD cloudinsight-agent.conf /etc/cloudinsight-agent/cloudinsight-agent.conf

