# Example - Complex
#
# Agent running with a more complex configuration

FROM oneapm/docker-oneapm-ci-agent

# Add a constom oneapm-ci-agent.conf
ADD oneapm-ci-agent.conf /etc/oneapm-ci-agent/oneapm-ci-agent.conf
